### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ouovouo** [Qquanwei/electron-webtoon#12]
未使用過舊版(2.3.1)時
2.3.2~2.3.6 都無法使用

2.3.2 雖有畫面，卻無法做任何事
![Snipaste_2022-07-25_20-03-59](https://user-images.githubusercontent.com/23149851/180775795-162fa5e5-679f-409c-9064-d673a0cc2a14.png)

2.3.3~2.3.6 畫面
![Snipaste_2022-07-25_19-37-42](https://user-images.githubusercontent.com/23149851/180775536-c49e7524-859d-4904-b4fc-155a5232574d.png)

解決方式:
安裝 2.3.1版 並 新增資料夾 再裝新版本就可以使用
(缺少%AppData%\electron-webtoon\.electron-webtton-comic.json 檔案)

**Comment by Qquanwei** [comment]
我的邮件过滤器把通知给过滤掉了！！导致没收到你的反馈，真的很sorry，我会尽快优化掉！！！

**Comment by Qquanwei** [comment]
感谢反馈，已在最新版修复 2.3.7
