### ISSUE TITLE
求大佬优化，排序规则希望能和windows名称排序一致

### ISSUE THREAD

**Issue by warmplay** [Qquanwei/electron-webtoon#14]
难得的好软件，就是不知道为什么经常排序是乱的，标准的001序列化没问题，但只要名称不是完全标准排序就可能会乱，例如正常的windows名称排序是“001第一章001”“001第一章002”“002第二章001”“002第二章002”，在软件看图时就会自动排序成“002第二章001”“002第二章002”“001第一章001”“001第一章002”，而且图片多可能更乱，另外希望可以加上分页功能。跪求大佬优化。

**Comment by Qquanwei** [comment]
我的邮件过滤器把通知给过滤掉了！！导致没收到你的反馈，真的很sorry，我会尽快优化掉！！！
