### ISSUE TITLE
目录为何是乱序显示？

### ISSUE THREAD

**Issue by uksask** [Qquanwei/electron-webtoon#15]
首先非常感谢您写了这个程序，我之前找能在电脑上丝滑看webtoon的程序找了好久……
建议您在标题或介绍中写上webtoon viewer或条漫阅读器，这样更容易被搜到。如果您不希望更多人搜到的话可以不用管我这条建议^_^

然后想说一下，我导入了两个文件夹，其中一个顺序基本是正确的，但另一个顺序是错误的，不知道是什么原因呢……
如下图所显示：
https://p.sda1.dev/8/5dbd024b36f87b4a861c9a443be38d1c/QQ截图20221109154346.png
https://p.sda1.dev/8/569453107a0780120ae053e77faa9fca/QQ截图20221109154409.png

此外是否方便加入顺序或倒序排列目录的功能？

**Comment by uksask** [comment]
再次冒昧打扰，我发现似乎是因为每一章节文件夹名称有中文的缘故，在去掉中文名称改为纯数字以后顺序正常了。
不知这算是bug吗？

**Comment by Qquanwei** [comment]
目前目录排序的时候规则是：

1. 将目录所有非数字剔除，然后做排序。
2. 检测到"最终" 目录权重会排到无限大权重，所以会移动到最后一个。

根据你的目录，由于是数字中夹带中文，所以实际上程序内部会理解成

1. 0001
2. 001494
3. 007634
4. ....

所以会导致错乱。。

**Comment by Qquanwei** [comment]
2.3.8 pre-release 已发布。

https://github.com/Qquanwei/electron-webtoon/releases
