### ISSUE TITLE
封面及章節問題

### ISSUE THREAD

**Issue by ouovouo** [Qquanwei/electron-webtoon#17]
封面圖片顏色過深時，漫畫名稱難以閱讀
![image](https://user-images.githubusercontent.com/23149851/216757348-58ff192b-fc49-4632-b8c3-60b32031565f.png)

資料夾名稱是 番外篇、外傳 章節順序會亂跳
![image](https://user-images.githubusercontent.com/23149851/216757537-e4ec273b-5d94-4341-b11e-009b7a7cf303.png)
![image](https://user-images.githubusercontent.com/23149851/216757525-133f2c82-6c5c-4e86-954a-5f98ea8f34f2.png)

**Comment by Qquanwei** [comment]
“番外” 这种场景，一般是应该比不带番外的靠前还是靠后呢？

可以作为一种特殊情况调整下优先级。

**Comment by ouovouo** [comment]
我目前碰到的都是本篇出完才出番外

**Comment by Qquanwei** [comment]
https://github.com/Qquanwei/electron-webtoon/commit/14d01bc28024e2b181de7e8c633937292996e154

**Comment by Qquanwei** [comment]
排序问题fix: https://github.com/Qquanwei/electron-webtoon/releases/tag/v2.3.9

**Comment by ouovouo** [comment]
番外權重*100 應該是不夠
![image](https://user-images.githubusercontent.com/23149851/217291198-06384a1f-be23-4ac8-9dde-2199b7f38336.png)
![image](https://user-images.githubusercontent.com/23149851/217291138-0e0ae2a1-3199-4f0a-8032-9b01f9506adc.png)

**Comment by Qquanwei** [comment]
hhh, 这么多章节啊，我再调大一点
