### ISSUE TITLE
章節資料夾同層目錄下有圖片會無法正常載入畫面

### ISSUE THREAD

**Issue by ouovouo** [Qquanwei/electron-webtoon#19]
原本漫畫資料夾下只有章節資料夾時可以正常使用

像：
漫畫
├─章節1─圖片
├─章節2─圖片
├─章節3─圖片
![image](https://user-images.githubusercontent.com/23149851/223784118-e2ed74ff-1c37-49e7-8a25-303df72c755f.png)

如果章節資料夾同層目錄下有圖片時，點進該漫畫會無法載入目錄畫面

漫畫
├─章節1─圖片
├─章節2─圖片
├─章節3─圖片
├─圖片
![image](https://user-images.githubusercontent.com/23149851/223783829-738831ba-ad96-486b-8099-3df1958d91d2.png)

![image](https://user-images.githubusercontent.com/23149851/223782663-ac1c3bd2-a6d1-4457-aafd-db0c56a1405a.png)

**Comment by Qquanwei** [comment]
GET

**Comment by Qquanwei** [comment]
另外我最近在全力开发这个软件，可以体验一下 https://github.com/Qquanwei/gante

**Comment by Qquanwei** [comment]
已经 release https://github.com/Qquanwei/electron-webtoon/releases/tag/v2.3.10
