### ISSUE TITLE
解释一下为什么延期那么久没更新...

### ISSUE THREAD

**Issue by Qquanwei** [Qquanwei/electron-webtoon#2]
1. 主要原因是家里的网络让我非常头痛，nvm, npm，yarn 安装失败，node-sass 这类老是报错，还有我emacs没办法拉到外部源安装插件，是目前阻塞的主要原因。
2. 自由时间不是很多
3. 一般不会在公司开发，平时工作也很忙，不会在上班时间维护。

目前在一点点的开发中，也想添加一些令人激动的特性，但是进度比较慢，如果你有在用也可以留言下，有人用的话会给我更大的动力。

**Comment by qingtianzaishang** [comment]
我觉得能不能读取压缩包里的图片才是这个桌面webtoon软件的核心需求之一。webtoon本身就是适配手机发展出来的产业，手机上并不缺这类成熟软件，例如perfectviewer；而ElectronWebtoon的应用对象，主要是玩漫Toomics这类太零碎，一张完整的页面切成小段，使图片数量激增而下载下来观看体验极差的漫画，其他漫画下载下来直接查看也影响不大。现在看漫画都是压缩包直接看，不然的话占空间臃肿不说还会影响机器扫描时的读取效率

**Comment by Qquanwei** [comment]
@qingtianzaishang 这个功能目前正在进行中，因为我也有很多是在压缩包里的，小文件拷贝起来速度太低，对我也是一个核心诉求。
这两天增加了移动端查看的功能（2.3.3 prerelease 可下载），可以直接扫码到手机上，也是核心需求之一。

**Comment by Qquanwei** [comment]
@qingtianzaishang 压缩包已支持。
