### ISSUE TITLE
漫画标题是几点几话的话，漫画顺序不正确（如129.5话）

### ISSUE THREAD

**Issue by namo1998** [Qquanwei/electron-webtoon#22]
发现如果标题是几点几话的话，漫画顺序不正确。
![E6U_YK8AE@UT(Z`A9RT`5@C](https://github.com/Qquanwei/electron-webtoon/assets/137674915/8880c737-9388-447c-8242-c622c0646015)

**Comment by Qquanwei** [comment]
收到

**Comment by Qquanwei** [comment]
https://github.com/Qquanwei/electron-webtoon/releases/tag/v2.3.11

**Comment by Qquanwei** [comment]
已修复，可以使用上面链接直接更新预览版。正式版会随后续更新上线。
