### ISSUE TITLE
请问自动更新后启动出现JavaScript Error

### ISSUE THREAD

**Issue by kogod8** [Qquanwei/electron-webtoon#23]
打开软件后提示会自动更新至.12版本，但是再打开的话会崩溃，如图。俺是代码小白，什么都看不懂，不知道应该怎么解决，求大佬帮助。
![屏幕截图 2024-03-17 170352](https://github.com/Qquanwei/electron-webtoon/assets/132798041/96ed4ae5-71a6-4de9-b2ab-90c57ae35a8d)

**Comment by Qquanwei** [comment]
已经收到，今晚修复

**Comment by Qquanwei** [comment]
https://github.com/Qquanwei/electron-webtoon/releases/  重新下载最新版本即可。构建机版本升级，导致产物和运行时匹配不上了。

**Comment by kogod8** [comment]
感谢大佬！！
