### ISSUE TITLE
新版本一个目录里只显示前100张图片，后面的不显示了，2.3.1不会有这个问题

### ISSUE THREAD

**Issue by warmplay** [Qquanwei/electron-webtoon#9]

**Comment by Qquanwei** [comment]
感谢反馈，待我验证下回复你

**Comment by Qquanwei** [comment]
@warmplay 👍  已验证，这是个功能bug，会在近两天内发出的新版本修复

**Comment by Qquanwei** [comment]
已修复 [Release v2.3.4](https://github.com/Qquanwei/electron-webtoon/releases/tag/v2.3.4)
